// <auto-generated />
using System;
using ConsoleProject.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleProject.Migrations
{
    [DbContext(typeof(CryptoAvenueContext))]
    partial class CryptoAvenueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConsoleProject.Domain.Coin", b =>
                {
                    b.Property<Guid>("CoinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValueInBTC")
                        .HasColumnType("float");

                    b.Property<double>("ValueInEUR")
                        .HasColumnType("float");

                    b.Property<double>("ValueInUSD")
                        .HasColumnType("float");

                    b.HasKey("CoinID");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
